##   Exception 

тЬЕ <b>Exception Handling </b> <br> 
тЬЕ <b>Exception Handling ржХрзАржнрж╛ржмрзЗ ржХрж╛ржЬ ржХрж░рзЗ? </b> <br>
C# ржП Exception Handling-ржПрж░ ржкрзНрж░ржзрж╛ржи рзйржЯрж┐ ржЕржВрж╢: try block, catch block, finally block 

ЁЯФ╣ <b>1. try Block тАУ рж╕ржирзНржжрзЗрж╣ржЬржиржХ ржХрзЛржб рж░рж╛ржЦрж╛ рж╣рзЯ </b>
<pre>
try 

{

int a = 10, b = 0; 
int c = a / b; // ржПржЦрж╛ржирзЗ exception рж╣ржмрзЗ
}
 </pre> 
ЁЯФ╕ try ржмрзНрж▓ржХрзЗ рж░рж╛ржЦрж╛ рж╣рзЯ рж╕рзЗржЗ ржХрзЛржб ржпрж╛ error ржмрж╛ exception ржШржЯрж╛рждрзЗ ржкрж╛рж░рзЗред

ЁЯФ╣ <b>2. Exception ржШржЯрж▓рзЗ CLR (Common Language Runtime) рж╕рзЗржЯрж╛ ржзрж░рзЗ C# ржП ржпржЦржи ржХрзЛржирзЛ runtime exception рж╣рзЯ (ржпрзЗржоржи 0 ржжрж┐рзЯрзЗ ржнрж╛ржЧ), рждржЦржи CLR: </b>
 * ржПржХржЯрж┐ Exception object рждрзИрж░рж┐ ржХрж░рзЗ
 * рж╕рзЗржЗ exception ржХрзЗ ржЙржкрж░рзЗрж░ ржжрж┐ржХрзЗ ржкрж╛ржарж╛рждрзЗ ржерж╛ржХрзЗ (Stack Unwinding)
 * ржЦрзЛржБржЬрзЗ ржХрзЛржирзЛ catch block ржЖржЫрзЗ ржХрж┐ ржирж╛

ЁЯФ╣ <b>3. catch Block тАУ Exception ржзрж░рж╛рж░ ржЬрж╛рзЯржЧрж╛ </b> 
<pre> 
catch (DivideByZeroException ex)

{

Console.WriteLine("Quotient not possible : " + ex.Message);
}
</pre>
ЁЯФ╕ catch ржмрзНрж▓ржХ рж╕рзЗржЗ ржХрзЛржб , ржпрзЗржЦрж╛ржирзЗ CLR exception ржкрж╛ржарж╛рзЯред ржЪрж╛ржЗрж▓рзЗ ржПржЦрж╛ржирзЗ exception handle ржХрж░рзЗ ржмрзНржпржмрж╣рж╛рж░ржХрж╛рж░рзАрж░ ржЬржирзНржп рж╕рзБржирзНржжрж░ ржорзЗрж╕рзЗржЬ ржкрж╛ржарж╛ржирзЛ ржпрж╛рзЯ ред

ЁЯФ╣ <b>4. finally Block тАУ рж╕ржмрж╢рзЗрж╖рзЗ ржпрзЗржЯрж╛ ржЪрж▓ржмрзЗржЗ </b>
<pre>
finally

{

Console.WriteLine("Operation complete.");
}
 </pre>
ЁЯФ╕ finally block рж╕ржмрж╕ржорзЯ ржЪрж▓ржмрзЗ тАУ exception рж╣рзЛржХ ржмрж╛ ржирж╛ рж╣рзЛржХред 

ЁЯФ╕ рж╕рж╛ржзрж╛рж░ржгржд ржПржЦрж╛ржирзЗ resource cleanup (file/database connection ржмржирзНржз ржХрж░рж╛) ржХрж░рж╛ рж╣рзЯред 

ЁЯФБ <b>Flow Chart </b> 
<pre> 
try тЖТ exception? тЖТ yes тЖТ catch тЖТ finally тЖТ resource cleanup
</pre>
ржЙржжрж╛рж╣рж░ржг:
<pre> 
try

{

string name = null;
Console.WriteLine(name.Length); // NullReferenceException
} catch (NullReferenceException ex)

{

Console.WriteLine("wrong : " + ex.Message);
}

finally

{

Console.WriteLine("Resource  Clean !");
}
</pre>
ЁЯФН<b> InnerException ржХрзАржнрж╛ржмрзЗ ржХрж╛ржЬ ржХрж░рзЗ? </b>  <br> 
InnerException C# ржПрж░ Exception class ржПрж░ ржПржХржЯрж┐ property, ржпрж╛ ржПржХржЯрж┐ exception ржПрж░ ржнрзЗрждрж░рзЗ ржЖрж░рзЗржХржЯрж┐ ржЖрж╕рж▓ exception ржХрзЗ ржзрж░рзЗ рж░рж╛ржЦрзЗред <br> 

ржПржЯрж┐ рждржЦржиржЗ ржжрж░ржХрж╛рж░ рж╣рзЯ, ржпржЦржи ржХрзЛржирзЛ ржмрзЬ ржмрж╛ complex error ржШржЯрж▓рзЗ, ржЖржорж░рж╛ рж╕рзЗржЗ ржорзВрж▓ ржнрзБрж▓ (root cause) ржмрж╛ ржЖрж╕рж▓ exception ржЬрж╛ржирж╛рж░ ржЪрзЗрж╖рзНржЯрж╛ ржХрж░рж┐ред  <br>   

тЬЕ <b>ржХрзЗржи InnerException ржжрж░ржХрж╛рж░? </b> <br> 
ЁЯСЙ ржзрж░рзБржи ржЖржкржирж┐ ржПржХржЯрж┐ ржлрж╛ржЗрж▓ read ржХрж░ржЫрзЗржи, ржХрж┐ржирзНрждрзБ рж╕рзЗ ржлрж╛ржЗрж▓ржЯрж┐ ржкрж╛ржУрзЯрж╛ ржпрж╛ржЪрзНржЫрзЗ ржирж╛ред ржПрж░ ржХрж╛рж░ржгрзЗ ржПржХржЯрж┐ FileNotFoundException рж╣ржмрзЗред ржЖржкржирж┐ ржпржжрж┐ ржПрж░ ржУржкрж░ ржЖрж░рзЗржХржЯрж┐ custom exception throw ржХрж░рзЗржи, рждрж╛рж╣рж▓рзЗ рж╕рзЗржЗ ржорзВрж▓ exception ржпрзЗржи рж╣рж╛рж░рж┐рзЯрзЗ ржирж╛ ржпрж╛рзЯтАФржПржЗ ржЬржирзНржп InnerException ржмрзНржпржмрж╣рж╛рж░ ржХрж░рж╛ рж╣рзЯред <br> 

ржЙржжрж╛рж░ржи :
<pre> 
try

{

try
{
    // main  exception
     int x = int.Parse("abc"); // FormatException

}

catch (FormatException ex)
{

    // ржЙржкрж░рзЗрж░ exception ржзрж░рзЗ ржирждрзБржи exception рждрзИрж░рж┐ ржХрж░рж╛ рж╣рж▓ 
    throw new ApplicationException("wong  data format ред", ex);

}
}

catch (ApplicationException ex)

{

Console.WriteLine("Main Exception: " + ex.Message);
Console.WriteLine("Root Cause (InnerException): " + ex.InnerException.Message);
}
</pre>
тЬЕ <b>Common Built-in Exception Classes in C# </b> <br>
<b>Exception Class Hierarchy : </b><br> 

ЁЯУМ System.Exception рж╕ржм exception ржХрзНрж▓рж╛рж╕рзЗрж░ ржорзВрж▓ ржнрж┐рждрзНрждрж┐ (base class)ред base class ржПрж░ ржорж╛ржзрзНржпржорзЗ рж╕ржХрж▓ exception ржЧрзБрж▓рзЛ рждрзИрж░рж┐ рж╣рзЯред <br>

тЪЩя╕П System.SystemException <br> 
Exception Class ржПржмржВ ржмрзНржпрж╛ржЦрзНржпрж╛  <br> 
рзз.ArgumentException => method-ржП invalid argument ржжрж┐рж▓рзЗ ржпрзЗржоржиржГ Path.GetFileName("*illegal?name"); <br>
рзи.ArgumentNullException => null argument ржжрж┐рж▓рзЗ ржпрзЗржоржиржГ File.ReadAllText(null);  <br> 
рзй.ArgumentOutOfRangeException => рж╕рзАржорж╛рж░ ржмрж╛ржЗрж░рзЗ argument ржжрж┐рж▓рзЗ ржпрзЗржоржиржГ list[100] ржпржЦржи list-ржП ржПржд item ржирзЗржЗ ржЕржерзНржпрж╛рзО list[101] ржпржжрж┐ ржПржХрзНрж╕рзЗрж╕ ржХрж░рждрзЗ ржЪрж╛ржЗ рждржЦржи ржПрж░рж░ ржжрж┐ржмрзЗ ред 

тЬЕ <b>рзк.ArithmeticException </b> 

тФФтФАтФА DivideByZeroException => int x = 10 / 0; рж╢рзВржирзНржп ржжрж┐рзЯрзЗ ржнрж╛ржЧ ржХрж░рж▓рзЗ

тФФтФАтФА OverflowException => рж╕рзАржорж╛ ржЫрж╛рзЬрж┐рзЯрзЗ ржЧрзЗрж▓рзЗ

рзл.IndexOutOfRangeException => Array ржмрж╛ list ржПрж░ рж╕рзАржорж╛рж░ ржмрж╛ржЗрж░рзЗ ржЧрзЗрж▓рзЗ ржпрзЗржоржиржГ int[] arr = new int[3]; var item = arr[5];

рзм. NullReferenceException => ржЕржерж╛рзО null object ржерзЗржХрзЗ access ржХрж░рж▓рзЗ ржпрзЗржоржиржГ string name = null; var length = name.Length;

рзн.InvalidCastException => ржЕржерж╛рзО ржЕржмрзИржз cast ржХрж░рж▓рзЗ ржпрзЗржоржиржГ object obj = "abc"; int i = (int)obj;

рзо.FormatException => ржнрзБрж▓ format рж╣рж▓рзЗ (ржпрзЗржоржи: int.Parse("abc"))

рзп.StackOverflowException => infinite recursion

рззрзж.OutOfMemoryException => ржЕржирзЗржХ ржмрзЬ data load ржХрж░рж╛рж░ рж╕ржорзЯ ржкрж░рзНржпрж╛ржкрзНржд ржорзЗржорзЛрж░рж┐ ржирж╛ ржерж╛ржХрж▓рзЗ

рззрзз.InvalidOperationException => object-ржПрж░ ржнрзБрж▓ ржЕржмрж╕рзНржерж╛ ржерзЗржХрзЗ call ржХрж░рж▓рзЗ

рззрзи.ObjectDisposedException => dispose рж╣рзЯрзЗ ржпрж╛ржУрзЯрж╛ object ржмрзНржпржмрж╣рж╛рж░ ржХрж░рж▓рзЗ

ЁЯУВ <b>System.IO.IOException </b> <br>
ржлрж╛ржЗрж▓, ржбрж┐рж░рзЗржХрзНржЯрж░рж┐ ржПржмржВ ржбрзНрж░рж╛ржЗржн рж╕ржВржХрзНрж░рж╛ржирзНржд Input/Output exceptionред

рзз.IOException => рж╕рж╛ржзрж╛рж░ржи IO рждрзНрж░рзБржЯрж┐

рзи.FileNotFoundException => ржлрж╛ржЗрж▓ ржЦрзБржБржЬрзЗ ржирж╛ ржкрзЗрж▓рзЗ

рзй.DirectoryNotFoundException =>ржбрж┐рж░рзЗржХрзНржЯрж░рж┐ ржирж╛ ржкрзЗрж▓рзЗ

рзк.PathTooLongException => ржкрж╛рже ржЕржирзЗржХ ржмрзЬ рж╣рж▓рзЗ

рзл.DriveNotFoundException => ржирж┐рж░рзНржжрж┐рж╖рзНржЯ ржбрзНрж░рж╛ржЗржн ржирж╛ ржкрзЗрж▓рзЗ

рзм.EndOfStreamException => stream-ржПрж░ рж╢рзЗрж╖ ржкрзМржБржЫрзЗ ржЧрзЗрж▓рзЗ

ЁЯФТ <b>Security and Access Exceptions </b> <br>
UnauthorizedAccessException => ржЕржирзБржорждрж┐ ржЫрж╛рзЬрж╛ resource access SecurityException => security policy рж▓ржЩрзНржШржи рж╣рж▓рзЗ

тП▒ <b>Async & Threading Exceptions </b>

рзз.OperationCanceledException => async ржХрж╛ржЬ cancel рж╣рж▓рзЗ

рзи.TaskCanceledException => Task cancel рж╣рж▓рзЗ

рзй.ThreadAbortException => ржерзНрж░рзЗржб ржЬрзЛрж░ржкрзВрж░рзНржмржХ ржмржирзНржз рж╣рж▓рзЗ

рзк.SynchronizationLockException => ржнрзБрж▓ ржнрж╛ржмрзЗ lock ржмрзНржпржмрж╣рж╛рж░рзЗ

ЁЯзй <b>Other Notable Exceptions </b> 
рзз.KeyNotFoundException => Dictionary-рждрзЗ key ржирж╛ ржкрзЗрж▓рзЗ

рзи.NotImplementedException => method implement ржирж╛ ржХрж░рж▓рзЗ

рзй.NotSupportedException => unsupported ржХрж╛ржЬрзЗрж░ ржЪрзЗрж╖рзНржЯрж╛

рзк.PlatformNotSupportedException => current OS/platform support ржирж╛ ржХрж░рж▓рзЗ

рзл.TimeoutException => ржирж┐рж░рзНржзрж╛рж░рж┐ржд рж╕ржорзЯ ржЕрждрж┐ржХрзНрж░ржо рж╣рж▓рзЗ

рзм.ApplicationException => custom application-level exception base (not recommended)
<br> 
ЁЯФД <b>Dispose() ржХрзА? </b>  <br>
тЬЕ рж╕ржВржЬрзНржЮрж╛ (Definition):

Dispose() рж╣рж▓рзЛ ржПржХржЯрж┐ method, ржпрж╛ unmanaged resources (ржпрзЗржоржи: file handles, database connections, network sockets ржЗрждрзНржпрж╛ржжрж┐) release ржХрж░рж╛рж░ ржЬржирзНржп ржмрзНржпржмрж╣рзГржд рж╣рзЯред <br> 

ржПржЯрж┐ IDisposable ржЗржирзНржЯрж╛рж░ржлрзЗрж╕рзЗрж░ ржЕржВрж╢ тАФ ржпрж╛рж░ ржорзВрж▓ ржЙржжрзНржжрзЗрж╢рзНржп рж╣рж▓рзЛ ржорзЗржорзЛрж░рж┐ ржмрж╛ рж░рж┐рж╕рзЛрж░рзНрж╕ рж▓рж┐ржХ ржкрзНрж░рждрж┐рж░рзЛржз ржХрж░рж╛ред

тЬЕ <b>Managed resource =></b> string, int, arrays => .NET CLR (Garbage Collector)

тЬЕ <b>Unmanaged resources =></b> File handles, DB connections, Win32 API resources,network sockets => Dispose() ржжрж┐рзЯрзЗ release ржХрж░рждрзЗ рж╣ржмрзЗ ред

ЁЯУж <b>IDisposable Interface: </b> 
<pre>
public interface IDisposable {

//  Performs application-defined tasks associated with freeing, 
releasing, or resetting  
//unmanaged resources.

void Dispose();
}
 </pre>
ржпрзЗ ржХрзНрж▓рж╛рж╕ржЯрж┐ IDisposable ржЗржирзНржЯрж╛рж░ржлрзЗрж╕ implement ржХрж░рзЗ, рж╕рзЗржЯрж┐ Dispose() method define ржХрж░рзЗ unmanaged resource free ржХрж░рждрзЗ ржкрж╛рж░рзЗред <br> 

ржЙржжрж╛рж╣рж░ржг:
<pre>
public class MyResource:IDisposable

{

 private FileStream file;

 public MyResource()

 {

     file = new FileStream("data.txt", FileMode.OpenOrCreate);

 }

 public void Dispose()

 {
    
     file.Dispose();
     Console.WriteLine("File resource released.");

 }
}
 </pre>
ЁЯФР <b>Using using Statement: </b> 
<pre> 
using (var reader = new StreamReader("data.txt"))

{

string line = reader.ReadLine();
}

// ржПржЦрж╛ржирзЗ reader.Dispose() ржЕржЯрзЛржорзЗржЯрж┐ржХ ржХрж▓ рж╣рзЯрзЗ ржпрж╛ржмрзЗ
</pre>
тЮбя╕П <b>using ржмрзНрж▓ржХ рж╢рзЗрж╖ рж╣рж▓рзЗ Dispose() ржирж┐ржЬрзЗ ржерзЗржХрзЗржЗ call рж╣рзЯрзЗ ржпрж╛рзЯ, ржХрзЛржирзЛ resource leak рж╣рзЯ ржирж╛ред </b>  <br> 
Object ржПрж░ lifecycle рж╢рзЗрж╖рзЗ (explicitly ржмрж╛ using ржжрж┐рзЯрзЗ) ржЪрж▓рзЗ. 

<br> <br> <br> <br> 


--------------------------------------------------------------------------------------------------------------------------------------


тЬЕ <b> Exception ржХрзА ? </b> <br> 
Exception ржорж╛ржирзЗ тАЬUnexpected errorтАЭ тАФ ржпрж╛ ржкрзНрж░рзЛржЧрзНрж░рж╛ржо ржЪрж▓рж╛рж░ рж╕ржорзЯ рж╣ржарж╛рзО ржШржЯрзЗ ржПржмржВ normal flow ржмржирзНржз ржХрж░рзЗ ржжрзЗрзЯред <br> 

ЁЯФ╖ <b>Exception Handling ржХрзЗржи ржжрж░ржХрж╛рж░? </b> <br> 

тЬЕ <b> Built-in Exception ржХрзА ? </b>  <br> 
Built-in Exception ржорж╛ржирзЗ тАФ ржпрзЗржЧрзБрж▓рзЛ .NET Framework ржирж┐ржЬрзЗрж░ ржнрзЗрждрж░рзЗржЗ define ржХрж░рж╛ ржЖржЫрзЗ (ржЖржорж╛ржжрзЗрж░ define ржХрж░рждрзЗ рж╣рзЯ ржирж╛)ред ржПржЗ Exception ржЧрзБрж▓рзЛ System.Exception class ржерзЗржХрзЗ derive ржХрж░рж╛ред <br>
> Namespace: System, System.IO, System.Net, System.Data, System.Xml


тЬЕ <b> try-catch-finally ржПрж░ ржХрж╛ржЬ : </b> <br> 
ЁЯФ╖ <b>try : </b> ржПржЦрж╛ржирзЗ risky ржмрж╛ error-prone code рж░рж╛ржЦрж╛ рж╣рзЯред ржпрзЗржоржи: Database connection, File I/O, API call, User input conversion. <br>
ЁЯФ╖ <b>catch : </b> ржпржжрж┐ try block ржП exception ржШржЯрзЗ, рждрж╛рж╣рж▓рзЗ control catch ржП ржЖрж╕рзЗред ржПржЦрж╛ржирзЗ рждрзБржорж┐ exception handle ржХрж░рждрзЗ ржкрж╛рж░рзЛ (log ржХрж░рж╛, custom message ржжрзЗржУрзЯрж╛, retry ржЗрждрзНржпрж╛ржжрж┐)ред <br> 
ЁЯФ╖ <b>finally : </b> finally block рж╕рж░рзНржмржжрж╛ execute рж╣рзЯ тАФ error рж╣рзЛржХ ржмрж╛ ржирж╛ рж╣рзЛржХред ржПржЦрж╛ржирзЗ clean-up ржХрж╛ржЬ ржХрж░рж╛ рж╣рзЯ: ржпрзЗржоржи file close ржХрж░рж╛, DB connection dispose ржХрж░рж╛ред <br> 

тЬЕ <b>ржХржЦржи use ржХрж░ржмрзЗ </b> 
<pre>
 ржкрж░рж┐рж╕рзНржерж┐рждрж┐	            |     Exception Handling ржжрж░ржХрж╛рж░?	       |        ржХрж╛рж░ржг
------------------------------------------------------------------------------------------------------------
User Input	          |         тЬЕ рж╣рзНржпрж╛ржБ	                       |   Invalid data (format, null, etc.)
File Handling	       |         тЬЕ рж╣рзНржпрж╛ржБ	                       |   File ржирж╛ ржкрж╛ржУрзЯрж╛, permission denied
Database Query	      |         тЬЕ рж╣рзНржпрж╛ржБ	                       |   DB connection fail, timeout, invalid data
Network Request	     |         тЬЕ рж╣рзНржпрж╛ржБ	                       |   Connection lost, API unavailable
Calculation	         |         тЪая╕П ржорж╛ржЭрзЗ ржорж╛ржЭрзЗ	                 |   Divide by zero, overflow
UI Event Handler	    |         тЬЕ	                           |   Prevent app crash on user action
Background service	  |         тЬЕ	                           |   Prevent service crash and log error
 </pre>

ЁЯФ╖ <b>Common Built-in Exception Classes </b> 
<pre>
Exception	               | ржШржЯрзЗ ржХрзЗржи	             | ржЙржжрж╛рж╣рж░ржг
------------------------------------------------------------------------------------------
DivideByZeroException	   | рж╢рзВржирзНржп ржжрж┐рзЯрзЗ ржнрж╛ржЧ	        | int x = 10 / 0;
NullReferenceException	  | null object access	  | string s = null; s.Length;
IndexOutOfRangeException	| array limit cross	   | arr[5] ржпржЦржи arr ржП рзйржЯрж╛ element
FormatException	         | invalid format	      | int.Parse("abc");
FileNotFoundException	   | ржлрж╛ржЗрж▓ ржирж╛ ржкрж╛ржУрзЯрж╛	       | File.ReadAllText("missing.txt");
InvalidCastException	    | ржнрзБрж▓ type cast	       | (int)"hello";
ArgumentNullException	   | null argument	       | File.ReadAllText(null);
OverflowException	       | numeric overflow	    | checked { int x = int.MaxValue + 1; }
InvalidOperationException| invalid state	       | e.g., closed connection use
TimeoutException	        | рж╕ржорзЯ рж╢рзЗрж╖	            | long DB query
OutOfMemoryException	    | ржорзЗржорзЛрж░рж┐ ржлрзБрж░рж┐рзЯрзЗ ржЧрзЗржЫрзЗ	   | ржмрзЬ object рждрзИрж░рж┐
StackOverflowException	  | infinite recursion	  | function self call
KeyNotFoundException	    | Dictionary key ржирзЗржЗ	  | dict["xyz"];
 </pre>






