## Exception 

тЬЕ <b> Exception ржХрзА ? </b> <br> 
Exception ржорж╛ржирзЗ тАЬUnexpected errorтАЭ тАФ ржпрж╛ ржкрзНрж░рзЛржЧрзНрж░рж╛ржо ржЪрж▓рж╛рж░ рж╕ржорзЯ рж╣ржарж╛рзО ржШржЯрзЗ ржПржмржВ normal flow ржмржирзНржз ржХрж░рзЗ ржжрзЗрзЯред <br> 

ЁЯФ╖ <b>Exception Handling ржХрзЗржи ржжрж░ржХрж╛рж░? </b> <br> 

тЬЕ <b> Built-in Exception ржХрзА ? </b>  <br> 
Built-in Exception ржорж╛ржирзЗ тАФ ржпрзЗржЧрзБрж▓рзЛ .NET Framework ржирж┐ржЬрзЗрж░ ржнрзЗрждрж░рзЗржЗ define ржХрж░рж╛ ржЖржЫрзЗ (ржЖржорж╛ржжрзЗрж░ define ржХрж░рждрзЗ рж╣рзЯ ржирж╛)ред ржПржЗ Exception ржЧрзБрж▓рзЛ System.Exception class ржерзЗржХрзЗ derive ржХрж░рж╛ред <br>
> Namespace: System, System.IO, System.Net, System.Data, System.Xml


тЬЕ <b> try-catch-finally ржПрж░ ржХрж╛ржЬ : </b> <br> 
ЁЯФ╖ <b>try : </b> ржПржЦрж╛ржирзЗ risky ржмрж╛ error-prone code рж░рж╛ржЦрж╛ рж╣рзЯред ржпрзЗржоржи: Database connection, File I/O, API call, User input conversion. <br>
ЁЯФ╖ <b>catch : </b> ржпржжрж┐ try block ржП exception ржШржЯрзЗ, рждрж╛рж╣рж▓рзЗ control catch ржП ржЖрж╕рзЗред ржПржЦрж╛ржирзЗ рждрзБржорж┐ exception handle ржХрж░рждрзЗ ржкрж╛рж░рзЛ (log ржХрж░рж╛, custom message ржжрзЗржУрзЯрж╛, retry ржЗрждрзНржпрж╛ржжрж┐)ред <br> 
ЁЯФ╖ <b>finally : </b> finally block рж╕рж░рзНржмржжрж╛ execute рж╣рзЯ тАФ error рж╣рзЛржХ ржмрж╛ ржирж╛ рж╣рзЛржХред ржПржЦрж╛ржирзЗ clean-up ржХрж╛ржЬ ржХрж░рж╛ рж╣рзЯ: ржпрзЗржоржи file close ржХрж░рж╛, DB connection dispose ржХрж░рж╛ред <br> 











